# Generated by Django 2.2.1 on 2019-05-08 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=500)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField()),
                ('image', models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('chest_girth', models.FloatField()),
                ('waist_circumference', models.FloatField()),
                ('hip_girth', models.FloatField()),
                ('body_type', models.CharField(max_length=200)),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=200)),
                ('has_coach', models.BooleanField(default=False)),
                ('allowed_from', models.TimeField()),
                ('allowed_until', models.TimeField()),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('image', models.CharField(default=None, max_length=400, null=True)),
                ('simulator_positions', models.IntegerField(default=None, null=True)),
                ('area', models.IntegerField(default=None, null=True)),
                ('best_sides', models.TextField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=1000)),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
                ('gym', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('work_days', models.CharField(max_length=200)),
                ('image', models.CharField(default=None, max_length=400, null=True)),
                ('price', models.IntegerField(default=None, null=True)),
                ('gym', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gym')),
            ],
            options={
                'verbose_name': 'coach',
                'verbose_name_plural': 'coaches',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='coach',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Coach'),
        ),
        migrations.AddField(
            model_name='client',
            name='gym',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gym'),
        ),
    ]
